version: "0.1.0"

services:
  # Collector
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: collector
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector/collector-config.yaml:/conf/collector-config.yaml
      - ./collector/metrics.json:/metrics.json
    ports:
      - "9464:9464" #prometheus
      - "4317:4317" #OLTP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      - PROMUSERNAME
      - PROMPASSWORD
      - PROMENDPOINT

  
  # Example Apps
  # Python
  flask_server:
    container_name: flask_server
    build:
      context: ./python
      dockerfile: ./examples/http_server/Dockerfile
    depends_on:
      collector:
        condition: service_started