extensions:
  basicauth/metrics:
    client_auth:
      username: 727351
      password: eyJrIjoiNWIwYzcxOWVhM2VmZjZkNzAzMWMzZGVlYTRhNmUyNDVhNWJmMzgyMCIsIm4iOiJjb2xsZWN0dGVzdCIsImlkIjo3NzU2NzN9

receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  file:
    path: ./metrics.json
  prometheusremotewrite:
    auth:
      authenticator: basicauth/metrics
    endpoint: https://prometheus-prod-05-gb-south-0.grafana.net/api/prom/push

service:
  extensions: [basicauth/metrics]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [file, prometheusremotewrite]