extensions:
  basicauth/metrics:
    client_auth:
      username: ${env:PROMUSERNAME}
      password: ${env:PROMPASSWORD}

receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "localhost:4318"
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  file:
    path: ./metrics.json
  prometheusremotewrite:
    auth:
      authenticator: basicauth/metrics
    endpoint: ${env:PROMENDPOINT}

service:
  extensions: [basicauth/metrics]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [file, prometheusremotewrite]